### ISSUE TITLE
Plugin Broken Following AWS Console UI Update

### ISSUE THREAD

**Issue by jtstrohl** [tilfin/aws-extend-switch-roles#156] opened 2020-09-15 02:18 UTC
This AWS Extend Switch Roles plugin, my most beloved Chrome plugin of all time, appears to be broken after an update was released to the AWS Console -- literally minutes ago.  All of the sudden, the username dropdown menu (top right) only displays the last 5 roles in my history and no longer displays my entire list of account/roles configured for the plugin, even though I have configured it to hide original role history.

I hope this is a simple fix!

**Comment by jtstrohl** [comment] 2020-09-15 02:20
Must have been a fluke.... After logging back into AWS, it's fixed.

**Comment by jtstrohl** [comment] 2020-09-15 02:26
OK, it's broken again..... I think they are releasing the UI update in a weighted-DNS distribution deployment, so sometimes it's the old and sometimes it's the new.

**Comment by jtstrohl** [comment] 2020-09-15 02:49
I discovered that the AWS Console UI update is only being rolled out to certain AWS accounts.  The extension works in accounts where it hasn't been rolled out, but is broken in those where it has.

**Comment by michal-adamkiewicz** [comment] 2020-09-15 08:57
confirm, broken on my side also 😢 😢 😢

**Comment by tobiasadam0770** [comment] 2020-09-15 10:52
Same here…

**Comment by ZCummings** [comment] 2020-09-15 13:47
same here -- works in accounts using the old UI, but not the new -- same behavior as reported above.

**Comment by kickasstimus** [comment] 2020-09-15 14:19
Part of the problem is that this id: `awsc-login-account-section` no longer exists, and so this

**Comment by mtamassia** [comment] 2020-09-15 19:10
Same issue / problem. Since AWS pushed their new experience (started yesterday) this add-on no longer works.

**Comment by kareemdarkazanli** [comment] 2020-09-15 19:55
Hi I’m with the AWS Console team and we’d like to help make it easier for this third-party extension to onboard with new navigation. We’ve sent an email to the author but if there’s a different method of contact or PoC please let me know. Thanks

**Comment by jlongman** [comment] 2020-09-16 00:53
@kareemdarkazanli is there a secret or is it something you can share?  At a certain point, anyone here can create a pull request to help the author get this done.

**Comment by tilfin** [comment] 2020-09-16 02:01
Firstly, now applying new navigation UI to my AWS Account by them.

**Comment by cgol** [comment] 2020-09-16 08:35
Can I raise a support call on AWS to put my account back to the old console until this plugin is updated?

**Comment by camlog** [comment] 2020-09-16 10:29
@kareemdarkazanli How long is the dashboard A/B testing going to continue?
Making a patch for this will be trickier whilst there are 2 versions of the dashboard in play.

**Comment by kickasstimus** [comment] 2020-09-16 13:23
> Can I raise a support call on AWS to put my account back to the old console until this plugin is updated?

I tried, but AWS isn't doing it. Since this is a 3rd party tool, and one that scrapes the UI to function, they don't have any obligation or desire to cater to it so the changes were not rolled back.

**Comment by kickasstimus** [comment] 2020-09-16 13:38
Once again, relevant xkcd: https://xkcd.com/2347/

**Comment by x3dfxjunkie** [comment] 2020-09-16 17:22
Just to add to this, when I first log in to AWS, it seems broken. If I manually switch roles, the add-on then starts to work.

**Comment by jjhatobjective** [comment] 2020-09-17 01:22
Is there a way to opt out of the new UI for accounts ? Our org uses this plugin pretty heavily and the few accounts that got the new UI are currently in chaos.

**Comment by jonathan-flowers** [comment] 2020-09-17 03:25
As mentioned above, it does appear that this is a full canary / A/B testing process that we are in the middle of. I am seeing random changes to the new UI depending on different roles / regions / accounts, without much consistency yet.  The only constant so far is that if I get the old UI, the extension works great. If I get the new UI, it breaks.

**Comment by jheller** [comment] 2020-09-17 03:35
Please, please please give us an opt-out. I *REALLY* need to be able to use this plugin as I have to deal with a lot of accounts via role switching, and without it I have to waste a lot of time. The standard UI is near useless.

**Comment by jheller** [comment] 2020-09-17 03:56
> > Can I raise a support call on AWS to put my account back to the old console until this plugin is updated?
> 
> I tried, but AWS isn't doing it. Since this is a 3rd party tool, and one that scrapes the UI to function, they don't have any obligation or desire to cater to it so the changes were not rolled back.

Then perhaps AWS should address this themselves and make the UI useable without the need for third party plugins. If you work with more than 5 roles, it's frustrating to use. Everyone I know uses this plugin.

**Comment by tilfin** [comment] 2020-09-17 09:16
First of all, I saw the phenomenon in my AWS Management Console.

It's not going to be a simple fix due to the impact of the change in style as well as the change in the rendering framework.
I have already communicated with the AWS developers via email about this issue.

Thank you for supporting those who have donated.

**Comment by simonscholeykcom** [comment] 2020-09-17 09:22
Thanks for the update, really appreciate it. Still don't understand why AWS don't have a better native solution...

**Comment by daknhh** [comment] 2020-09-17 09:28
After manually assuming a role and reloading the page the plugin is working again.

**Comment by simonscholeykcom** [comment] 2020-09-17 09:30
@daknhh is that because you are switching into an account that doesn't have the new console applied yet? i have just tried switching and i then get a working extend switch roles but as soon as I switch back to another account with the new UI I lose it again.

**Comment by daknhh** [comment] 2020-09-17 09:41
@simonscholeykcom No, its part of the same AWS Organization and this account has also the new UI applied.

**Comment by camlog** [comment] 2020-09-17 09:55
I've just escalated this through our Technical Account Manager and via a support case too.
Sounds like they are keen to either work with @tilfin or to raise a request for feature parity in the Dashboard.

**Comment by 0x91** [comment] 2020-09-17 11:37
> I've just escalated this through our Technical Account Manager and via a support case too.
> Sounds like they are keen to either work with @tilfin or to raise a request for feature parity in the Dashboard.

Ditto

**Comment by tilfin** [comment] 2020-09-17 13:07
It seems that it is very difficult to apply new stylesheet to the inserted role list items. The reason is that the new UI class name is a random value by the UI framework.

So I have to think of another way and have to reduce some features.

**Comment by cstavro** [comment] 2020-09-17 13:25
@tilfin 
There is likely a better way to do this but if you made a first pass to add your own className to the Role History element, that might negate having to go through and change the rest of the extension as it would just _find_ what it needs to carry on?

Something like: 

`[...document.querySelectorAll("div")].filter(n => n.childElementCount == 0).filter(n => n.innerText == "Role History")[0].parentElement.className += " cstavro-test"
`

**Comment by kormikez** [comment] 2020-09-17 16:49
So after just 3 days this issue has been upvoted over 80 times already, whereas on Firefox Add-Ons page and Chrome Web Store this priceless plugin has got only 50 reviews altogether (17 for FF, 33 for Chrome). Don't you guys think we owe @tilfin at least some appreciation? ;)

**Comment by jlongman** [comment] 2020-09-17 17:24
As a workaround I’ve been putting my cross account role names into my password manager. 

This is still slicker, as I can colour code and add danger emojis for certain roles and make them visible in the Console.

**Comment by kickasstimus** [comment] 2020-09-17 17:31
> So after just 3 days this issue has been upvoted over 80 times already, whereas on Firefox Add-Ons page and Chrome Web Store this priceless plugin has got only 50 reviews altogether (17 for FF, 33 for Chrome). Don't you guys think we owe @tilfin at least some appreciation? ;)

@tilfin do you have a donation page? If not I think we (the community) need to come together and compensate you for this so I'm setting up a GoFundMe. Whatever it earns, 100% goes to you. You've earned it.

**Comment by cstavro** [comment] 2020-09-17 17:35
@kickasstimus donation information is in the readme. A new donation page run by an unrelated party sounds sketchy to me.

**Comment by kickasstimus** [comment] 2020-09-17 17:43
> @kickasstimus donation information is in the readme. A new donation page run by an unrelated party sounds sketchy to me.

Good point -- anyway I can transfer this to something less me and more tilfin? I'm all for other ideas, too.

**Comment by kickasstimus** [comment] 2020-09-17 17:44
> @kickasstimus donation information is in the readme. A new donation page run by an unrelated party sounds sketchy to me.

Doh! I totally missed that. Yeah -- do that instead. I'll wrap up the above and send the donation to his preferred method.

**Comment by kareemdarkazanli** [comment] 2020-09-18 03:08
Thank you for your patience. We’ve pushed out changes to new navigation that would help support the functionality of this extension (the css still needs some updates). We can support @tilfin if he needs to make the css fixes, but the extension should now be functional.

**Comment by oappicgi** [comment] 2020-09-18 06:55
first, thanks tilfin for making such a great plugin. 

it is bit of a shame that AWS console is somewhat horrible in that regard and hasn't really changed in 4 years I have been working with AWS.

**Comment by simonscholeykcom** [comment] 2020-09-18 07:11
Working for me. Thank you to all involved.

**Comment by timschill** [comment] 2020-09-18 07:45
Im still having no luck on getting this plugin to work. Could it have anything todo with my config? I have divided it like this:
`[master-account-1]
aws_account_id = master-account-1

[profile master1-child1]
role_arn = arn:aws:iam::00000000000:role/My-Role
region = eu-west-1
source_profile = master-account-1
color=ff9300

[profile master1-child2]
role_arn = arn:aws:iam::0000000000:role/My-Role
region = eu-west-1
source_profile = master-account-1
color=ff9300

[master-account-2]
aws_account_id = master-account-2

[profile im-agp]
role_arn = arn:aws:iam::000000000000:role/My-Role
region = eu-north-1
source_profile = master-account-2
color=ff9300
`

**Comment by yannickvr** [comment] 2020-09-18 07:53
> 
> 
> Im still having no luck on getting this plugin to work. Could it have anything todo with my config? I have divided it like this:
> `[master-account-1]
> aws_account_id = master-account-1
> 
> [profile master1-child1]
> role_arn = arn:aws:iam::00000000000:role/My-Role
> region = eu-west-1
> source_profile = master-account-1
> color=ff9300
> 
> [profile master1-child2]
> role_arn = arn:aws:iam::0000000000:role/My-Role
> region = eu-west-1
> source_profile = master-account-1
> color=ff9300
> 
> [master-account-2]
> aws_account_id = master-account-2
> 
> [profile im-agp]
> role_arn = arn:aws:iam::000000000000:role/My-Role
> region = eu-north-1
> source_profile = master-account-2
> color=ff9300
> `

Plugin is still mostly broken currently if you have the new UI. Few days of patience needed probably.

**Comment by kirnberger1980** [comment] 2020-09-18 08:39
Love this plugin and would like to still use it with the new console UI.

**Comment by goyertp** [comment] 2020-09-18 08:40
I really appreciate your time developing this plugin.
An update would be cool :-)

Thanks / MErci / Danke / Gracias / Obrigado

**Comment by tilfin** [comment] 2020-09-18 08:47
@timcleaver @yannickvr The complex configuration does not work in New UI after https://github.com/tilfin/aws-extend-switch-roles/issues/156#issuecomment-694621913

https://github.com/tilfin/aws-extend-switch-roles#simple-configuration
Please change to the above temporarily and save the original settings somewhere.

**Comment by simonscholeykcom** [comment] 2020-09-18 08:51
I am using the simple config and it works fine.

**Comment by tilfin** [comment] 2020-09-18 08:53
This is a thing I've been thinking about, but it's less affected by showing the role list from the extension browser icon instead of hacking the list in the Console page. So I'm moving it to break through the issue.

**Comment by paulalex** [comment] 2020-09-18 11:44
I have noticed this since this morning, when I hit my landing zone account all is well, when I switch roles its broken but also I noticed that all my pinned services in chrome are no longer there, not related to this plugin but just something else I am noting.

**Comment by trcgravert** [comment] 2020-09-18 11:52
> 
> 
> I have noticed this since this morning, when I hit my landing zone account all is well, when I switch roles its broken but also I noticed that all my pinned services in chrome are no longer there, not related to this plugin but just something else I am noting.

I fear that's by AWS design. The pins are now your favorites in the dropdown menu. I'm not too fond of these changes.

**Comment by jtstrohl** [comment] 2020-09-18 12:07
I'm a huge fan of AWS, but I'm not too fond of a lot of the changes in
these "New UI Experiences" being released lately.  Most people don't like
changes to their UI unless there are significant usability benefits.... If
it ain't broke, don't fix it!

**Comment by paulalex** [comment] 2020-09-18 12:15
> I fear that's by AWS design. The pins are now your favorites in the dropdown menu. I'm not too fond of these changes.

Indeed they are, thank you for pointing that out, I prefer them where they were if I am honest as now I need to click the "Services" link to get to the favourites, the entire reason I pinned them in the first place!

**Comment by jtstrohl** [comment] 2020-09-18 12:28
Exactly what I don't like about the new UIs... Less efficient use of screen
real estate, more clicks and scrolling required than before, especially for
repetitive tasks.  Information is more separated and hidden and hard to
find.  I prefer higher information density.  The new UIs are pretty, no
doubt, but less intuitive and less functional/efficient IMHO.  Who moved my
cheese?!

**Comment by tilfin** [comment] 2020-09-18 14:50
I pre-released AESR V2, you can get zip files of it in https://github.com/tilfin/aws-extend-switch-roles/pull/157#issuecomment-694912913

**Comment by daveofthedogs** [comment] 2020-09-18 15:27
> > I have noticed this since this morning, when I hit my landing zone account all is well, when I switch roles its broken but also I noticed that all my pinned services in chrome are no longer there, not related to this plugin but just something else I am noting.
> 
> I fear that's by AWS design. The pins are now your favorites in the dropdown menu. I'm not too fond of these changes.

Is ANYBODY fond of the UI changes? They have all been crap.

**Comment by msuchy-janrain** [comment] 2020-09-18 15:36
> I pre-released AESR V2, you can get zip files of it in [#157 (comment)](https://github.com/tilfin/aws-extend-switch-roles/pull/157#issuecomment-694912913)

I don't recall when was the last time I was so happy about any pre-release/update. You sir, just saved our lives from eternal torment of crappy UI.

**Comment by Yuxael** [comment] 2020-09-18 15:40
> I pre-released AESR V2, you can get zip files of it in [#157 (comment)](https://github.com/tilfin/aws-extend-switch-roles/pull/157#issuecomment-694912913)

I don't recall when was the last time I was so happy about any pre-release/update. You sir, just saved our lives from eternal torment of crappy UI.

**Comment by jolcese** [comment] 2020-09-18 16:41
> I pre-released AESR V2, you can get zip files of it in [#157 (comment)](https://github.com/tilfin/aws-extend-switch-roles/pull/157#issuecomment-694912913)

Does it work with both simple and complex mode? It's not working for me on complex mode?

**Comment by EricZaporzan** [comment] 2020-09-18 16:59
> > I pre-released AESR V2, you can get zip files of it in [#157 (comment)](https://github.com/tilfin/aws-extend-switch-roles/pull/157#issuecomment-694912913)
> 
> Does it work with both simple and complex mode? It's not working for me on complex mode?

I didn't realize at first that now you need to click the extension icon rather than the dropdown in the console. Works great for me in complex mode. Maybe that's the issue @jolcese?

**Comment by jolcese** [comment] 2020-09-19 23:44
> > > I pre-released AESR V2, you can get zip files of it in [#157 (comment)](https://github.com/tilfin/aws-extend-switch-roles/pull/157#issuecomment-694912913)
> > 
> > 
> > Does it work with both simple and complex mode? It's not working for me on complex mode?
> 
> I didn't realize at first that now you need to click the extension icon rather than the dropdown in the console. Works great for me in complex mode. Maybe that's the issue @jolcese?

Thanks. Now sure why but now it's working on both Simple and Complex modes.

**Comment by tilfin** [comment] 2020-09-20 10:22
Please comment the feeback about V2 to #157 after this.

**Comment by GeoffMillerAZ** [comment] 2020-09-21 18:02
It would be nice if the extension added a menu to the extension icon when you click it. The menu could have all the functionality you'd expect from a working UI. That way if the UI overload isn't working you can still get the function of the plugin.

**Comment by dodgyd** [comment] 2020-09-22 06:05
> Im still having no luck on getting this plugin to work. Could it have anything todo with my config? I have divided it like this:
> 
> ```
> [master-account-1]
> aws_account_id = master-account-1
> 
> [profile master1-child1]
> role_arn = arn:aws:iam::00000000000:role/My-Role
> region = eu-west-1
> source_profile = master-account-1
> color=ff9300
> 
> [profile master1-child2]
> role_arn = arn:aws:iam::0000000000:role/My-Role
> region = eu-west-1
> source_profile = master-account-1
> color=ff9300
> 
> [master-account-2]
> aws_account_id = master-account-2
> 
> [profile im-agp]
> role_arn = arn:aws:iam::000000000000:role/My-Role
> region = eu-north-1
> source_profile = master-account-2
> color=ff9300
> ```

Temporarily remark  ; the source_profile lines until the fix is released.

**Comment by timschill** [comment] 2020-09-22 06:53
> > Im still having no luck on getting this plugin to work. Could it have anything todo with my config? I have divided it like this:
> > ```
> > [master-account-1]
> > aws_account_id = master-account-1
> > 
> > [profile master1-child1]
> > role_arn = arn:aws:iam::00000000000:role/My-Role
> > region = eu-west-1
> > source_profile = master-account-1
> > color=ff9300
> > 
> > [profile master1-child2]
> > role_arn = arn:aws:iam::0000000000:role/My-Role
> > region = eu-west-1
> > source_profile = master-account-1
> > color=ff9300
> > 
> > [master-account-2]
> > aws_account_id = master-account-2
> > 
> > [profile im-agp]
> > role_arn = arn:aws:iam::000000000000:role/My-Role
> > region = eu-north-1
> > source_profile = master-account-2
> > color=ff9300
> > ```
> 
> Temporarily remark ; the source_profile lines until the fix is released.

Thank you, this resolved the issue where I could jump from master account to one account but not assume a role on another account from any other account then our master.
Remarking the source_profile now let me assume a role and jumping around like Im used to do. Only thing is that my color matching doesn't  work in the config now. A small price to pay I guess.

**Comment by tilfin** [comment] 2020-09-22 08:23
I pre-released AESR V2.0.1 (rev updated), you can get zip files of it in #157 (comment)

**Comment by thiezn** [comment] 2020-09-23 09:57
> Hi I’m with the AWS Console team and we’d like to help make it easier for this third-party extension to onboard with new navigation. We’ve sent an email to the author but if there’s a different method of contact or PoC please let me know. Thanks

@kareemdarkazanli great that you're reaching out! I suspect a lot of customers having more than 5 accounts (every enterprise out there?) uses this plugin. Instead of an external plugin, it would be even better if this can be integrated natively into the AWS console. Is there an easy way for the community to raise a request and upvote this feature?

**Comment by tilfin** [comment] 2020-09-23 14:40
I pre-released AESR V2.0.2 (rev updated), you can get zip files of it in https://github.com/tilfin/aws-extend-switch-roles/pull/157#issuecomment-694912913,

**Comment by jack1902** [comment] 2020-09-23 15:10
@kareemdarkazanli One point to note as to why this plugin is so useful is that it enables orgs/teams to provide a pre-populated file to hit the ground running. If this plugin was native to the console, it would:

- Lack the support for a pre-populated list via a config file
- Survive off of cookies 😢 (i clear my cookies on browser close)

@tilfin thanks for your continued work, since i have used AWS, i have used this plugin/extension

**Comment by RWMulayAhmed** [comment] 2020-09-23 16:16
What appeared to work for me is switching the role manually once by clicking on switch role and type **AccountID**, **ROLE_ARN**, and **DisplayName**. All the accounts switch roles seemed to work.

**Comment by rrkraft** [comment] 2020-09-23 18:16
> I pre-released AESR V2.0.2 (rev updated), you can get zip files of it in [#157 (comment)](https://github.com/tilfin/aws-extend-switch-roles/pull/157#issuecomment-694912913),

Do you know when you will push this into the official Chrome and Firefox extension stores? My company blocks me from using anything outside of the store and I really need this extension. We have over 150 accounts and some of us have to switch constantly between them.

**Comment by pjwiseman** [comment] 2020-09-24 01:24
I've only recently found the "Automatically assume last assumed role (Experimental)" option.  That's now also broken - it keeps switching to the last role continuously.

**Comment by tilfin** [comment] 2020-09-24 02:28
I haven't settled on a clean situation, but the barriers are gone for now and I've released AESR V2.0.3 to the store.

#### Chrome
In review in Chrome Web Store
you can get zip files of it in https://github.com/tilfin/aws-extend-switch-roles/pull/157#issuecomment-694912913

#### Firefox
Now available in Firefox Browser ADD-ONS
https://addons.mozilla.org/ja/firefox/addon/aws-extend-switch-roles3/

**Comment by pjonesIDBS** [comment] 2020-09-24 10:05
@tilfin Many thanks for the new version! It's working nicely for us :)

**Comment by tilfin** [comment] 2020-09-24 10:17
If you have a GitHub account, you can star this repositories. This action will contribute to the standing of my engineer.

**Comment by jack1902** [comment] 2020-09-24 13:27
@tilfin the irony in this breaking is that you have gained a few stars and exposure to this repo:
http://www.gitstarhistory.com/#tilfin/aws-extend-switch-roles
<img width="1072" alt="Screenshot 2020-09-24 at 14 27 34" src="https://user-images.githubusercontent.com/39212456/94151253-17f6d280-fe72-11ea-9980-6b95116a7e42.png">

**Comment by askaem** [comment] 2020-09-25 15:00
Is there a way to downgrade back to the prior version?  I'm sure they will eventually roll out the UI changes to GovCloud, but for now that's all I work in and the update definitely doesn't work in GovCloud. Thanks again for creating this - it's a huge time saver!

**Comment by tilfin** [comment] 2020-09-25 15:04
@askaem See the above https://github.com/tilfin/aws-extend-switch-roles/issues/156#issuecomment-698073728

**Comment by kintax** [comment] 2020-09-25 15:26
Hi,  

I created a new Chrome profile, installed the plugin, and copied my config from my old profile, but it doesn't seem to work:

![image](https://user-images.githubusercontent.com/7110663/94285592-daea1900-ff21-11ea-87d2-4ee0c95acf36.png)

I updated the plugin in my usual Chrome profile, it works but looks funky, sae as it did a few days ago before the fix... 
![image](https://user-images.githubusercontent.com/7110663/94285405-99f20480-ff21-11ea-9c3e-3f120e818f04.png)

**Comment by kintax** [comment] 2020-09-25 15:27
Hi,  

I created a new Chrome profile, installed the plugin, and copied my config from my old profile, but it doesn't seem to work:

![image](https://user-images.githubusercontent.com/7110663/94285592-daea1900-ff21-11ea-87d2-4ee0c95acf36.png)

I updated the plugin in my usual Chrome profile, it works but looks funky, sae as it did a few days ago before the fix... 
![image](https://user-images.githubusercontent.com/7110663/94285677-fce39b80-ff21-11ea-93e4-719d2719c035.png)

**Comment by kintax** [comment] 2020-09-25 15:29
Hi,  

I created a new Chrome profile, installed the plugin, and copied my config from my old profile, but it doesn't seem to work:

![image](https://user-images.githubusercontent.com/7110663/94285874-4af89f00-ff22-11ea-9eba-ef20af84552f.png)


I updated the plugin in my usual Chrome profile, it works but looks funky, sae as it did a few days ago before the fix... 

![image](https://user-images.githubusercontent.com/7110663/94285886-4e8c2600-ff22-11ea-953e-84910fc1102e.png)

**Comment by kintax** [comment] 2020-09-25 15:34
Hi,

At my company we're still having issues.  When I use my normal Chrome I see my roles and things work, it just looks funky still, which is nbd.

![image](https://user-images.githubusercontent.com/7110663/94286400-f30e6800-ff22-11ea-9ff6-badf3be6ceb9.png)

But when I create a new Chrome profile, install the plugin, and copy the config from my first profile, it doesn't seem to work:

![image](https://user-images.githubusercontent.com/7110663/94286451-03bede00-ff23-11ea-8c17-72d69381f109.png)

**Comment by kintax** [comment] 2020-09-25 15:41
Ok, I found that my new profile's plugin works after I manually switch roles one time.

**Comment by tilfin** [comment] 2020-09-25 16:43
Feel free to issue new one with **V2** label.

**Closed** 2020-09-26 15:27 UTC
Labels: V2
